services:
  postgresql:
    container_name: postgresql
    image: postgres:16-alpine
    expose:
      - '5432'
    env_file: ./backend/.env
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chat-network
  backend:
    container_name: auth_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - '8000'
    env_file: ./backend/.env
    volumes:
      - ./backend:/application
    restart: unless-stopped
    command: sh -c 'alembic upgrade head && python -u -m uvicorn main:application --host 0.0.0.0 --port 8000'
    networks:
      - chat-network
    depends_on:
      - postgresql

networks:
  chat-network:
    driver: bridge
    external: true

volumes:
  data:
